// Markdown for text cells, with $inline$ and $$display$$ math rendered by KaTeX.
// Write \$ for a plain dollar sign ("costs \$20" shows "costs $20").

import DOMPurify from 'dompurify';
import katex from 'katex';
import { marked } from 'marked';

const MATH_RE = /\$\$([\s\S]+?)\$\$|\$([^$\n]+?)\$/g;
/** Stands in for an escaped \$ while math is found, so it can't start or end a formula. */
const DOLLAR = 'DOLLARSIGNPLACEHOLDERX';

export interface MathSegment {
  tex: string;
  display: boolean;
}

/**
 * Pull the $…$ and $$…$$ formulas out of a text cell, leaving numbered placeholders.
 * An escaped \$ is never part of a formula's edges; inside a formula it stays \$ (a dollar sign in LaTeX).
 */
export function splitMath(text: string): { text: string; segments: MathSegment[] } {
  const segments: MathSegment[] = [];
  const out = text.replace(/\\\$/g, DOLLAR).replace(MATH_RE, (_m, display: string | undefined, inline: string | undefined) => {
    segments.push({ tex: (display ?? inline ?? '').split(DOLLAR).join('\\$'), display: display !== undefined });
    return `MATHPLACEHOLDER${segments.length - 1}X`;
  });
  return { text: out, segments };
}

export function renderMarkdown(text: string): string {
  const { text: withPlaceholders, segments } = splitMath(text);
  const math = segments.map((s) => katex.renderToString(s.tex, { displayMode: s.display, throwOnError: false }));
  const html = DOMPurify.sanitize(marked.parse(withPlaceholders, { async: false, breaks: true }) as string);
  // KaTeX output is generated by us from plain text (trust is off), so it is inserted after sanitizing.
  return html
    .replace(/MATHPLACEHOLDER(\d+)X/g, (_m, i) => math[Number(i)] ?? '')
    .split(DOLLAR).join('$');
}
