// Markdown for text cells, with $inline$ and $$display$$ math rendered by KaTeX.
// Write \$ for a plain dollar sign ("costs \$20" shows "costs $20").

import DOMPurify from 'dompurify';
import katex from 'katex';
import { marked } from 'marked';
import { notebookHash } from './routes';

const MATH_RE = /\$\$([\s\S]+?)\$\$|\$([^$\n]+?)\$/g;
/** Stands in for an escaped \$ while math is found, so it can't start or end a formula. */
const DOLLAR = 'DOLLARSIGNPLACEHOLDERX';

export interface MathSegment {
  tex: string;
  display: boolean;
}

/**
 * Pull the $…$ and $$…$$ formulas out of a text cell, leaving numbered placeholders.
 * An escaped \$ is never part of a formula's edges; inside a formula it stays \$ (a dollar sign in LaTeX).
 */
export function splitMath(text: string): { text: string; segments: MathSegment[] } {
  const segments: MathSegment[] = [];
  const out = text.replace(/\\\$/g, DOLLAR).replace(MATH_RE, (_m, display: string | undefined, inline: string | undefined) => {
    segments.push({ tex: (display ?? inline ?? '').split(DOLLAR).join('\\$'), display: display !== undefined });
    return `MATHPLACEHOLDER${segments.length - 1}X`;
  });
  return { text: out, segments };
}

/**
 * A link to another notebook, written [[Chapter 6 - Systems]], [[Chapter 6 - Systems|Systems of equations]],
 * [[Chapter 6 - Systems#Lesson 2]] (a section, by the start of its divider's title) or [[#Lesson 2]]
 * (a section of this notebook). Names are relative to the notebook's folder; start with / for the top level.
 */
export interface NotebookLink {
  /** The notebook's path in the journal ('' = this notebook). */
  name: string;
  section: string;
  label: string;
}

/** Code spans and blocks (group 1), or a [[link]] (group 2) — so links inside code are skipped. */
const CODE_OR_WIKI_RE = /(`+)[\s\S]*?\1|\[\[([^\[\]\n]+?)\]\]/g;

/** Read the inside of [[…]], resolving the name against `folder` (the linking notebook's folder). */
export function parseNotebookLink(inner: string, folder: string): NotebookLink | null {
  const [target, shown] = inner.split('|');
  const hash = target.indexOf('#');
  const rawName = (hash >= 0 ? target.slice(0, hash) : target).trim();
  const section = hash >= 0 ? target.slice(hash + 1).trim() : '';
  if (!rawName && !section) return null;
  const name = !rawName ? '' : rawName.startsWith('/') ? rawName.slice(1) : folder ? `${folder}/${rawName}` : rawName;
  const label = shown?.trim() || (rawName ? rawName.split('/').pop()! : '') + (section ? `${rawName ? ' › ' : ''}${section}` : '');
  return { name, section, label };
}

const escapeHtml = (s: string) => s.replace(/[&<>"']/g, (c) => `&#${c.charCodeAt(0)};`);

export function renderMarkdown(text: string, opts: { folder?: string } = {}): string {
  // Notebook links become placeholders first, so a | inside [[…]] can't break a table.
  const links: NotebookLink[] = [];
  // Code (`…` or ``` blocks) is left as typed, so `[[Name]]` can show how to write a link.
  const withLinks = text.replace(CODE_OR_WIKI_RE, (whole, code: string | undefined, inner: string | undefined) => {
    if (code !== undefined || inner === undefined) return whole;
    const link = parseNotebookLink(inner, opts.folder ?? '');
    if (!link) return whole;
    links.push(link);
    return `NBLINKPLACEHOLDER${links.length - 1}X`;
  });
  const { text: withPlaceholders, segments } = splitMath(withLinks);
  const math = segments.map((s) => katex.renderToString(s.tex, { displayMode: s.display, throwOnError: false }));
  const html = DOMPurify.sanitize(marked.parse(withPlaceholders, { async: false, breaks: true }) as string);
  // KaTeX output and notebook links are generated by us from plain text, so they are inserted after sanitizing.
  return html
    .replace(/MATHPLACEHOLDER(\d+)X/g, (_m, i) => math[Number(i)] ?? '')
    .replace(/NBLINKPLACEHOLDER(\d+)X/g, (_m, i) => {
      const l = links[Number(i)];
      if (!l) return '';
      return `<a class="notebook-link" href="${escapeHtml(notebookHash(l.name, l.section ?? ''))}" data-nb="${escapeHtml(l.name)}" `
        + `data-section="${escapeHtml(l.section)}">${escapeHtml(l.label)}</a>`;
    })
    .split(DOLLAR).join('$');
}
