// Markdown for text cells, with $inline$ and $$display$$ math rendered by KaTeX.

import DOMPurify from 'dompurify';
import katex from 'katex';
import { marked } from 'marked';

const MATH_RE = /\$\$([\s\S]+?)\$\$|\$([^$\n]+?)\$/g;

export function renderMarkdown(text: string): string {
  const math: string[] = [];
  const withPlaceholders = text.replace(MATH_RE, (_m, display: string | undefined, inline: string | undefined) => {
    const tex = display ?? inline ?? '';
    math.push(katex.renderToString(tex, { displayMode: display !== undefined, throwOnError: false }));
    return `MATHPLACEHOLDER${math.length - 1}X`;
  });
  const html = DOMPurify.sanitize(marked.parse(withPlaceholders, { async: false, breaks: true }) as string);
  // KaTeX output is generated by us from plain text (trust is off), so it is inserted after sanitizing.
  return html.replace(/MATHPLACEHOLDER(\d+)X/g, (_m, i) => math[Number(i)] ?? '');
}
